/*
 * File: app/view/Gallery.js
 *
 * This file was generated by Sencha Architect version 2.3.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.Gallery', {
    extend: 'Ext.window.Window',
    alias: 'widget.gallery',

    cls: 'gallery',
    height: 350,
    itemId: 'gallery',
    width: 600,
    layout: {
        type: 'border'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            bodyCls: [
                'x-window-body-default',
                'x-border-layout-ct',
                'x-closable',
                'x-window-body-closable',
                'x-window-body-default-closable'
            ],
            items: [
                {
                    xtype: 'panel',
                    region: 'west',
                    itemId: 'menuPanel',
                    width: 120,
                    layout: {
                        type: 'fit'
                    },
                    items: [
                        {
                            xtype: 'menu',
                            floating: false,
                            itemId: 'menu',
                            width: 120,
                            plain: true,
                            items: [
                                {
                                    xtype: 'menuitem',
                                    text: 'Basic'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Layouts'
                                },
                                {
                                    xtype: 'menuitem',
                                    text: 'Starter Apps'
                                }
                            ]
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'itemPanel',
                    autoScroll: true,
                    items: [
                        {
                            xtype: 'dataview',
                            itemId: 'items',
                            padding: 10,
                            emptyText: 'No items found',
                            itemSelector: 'div.gallery-item',
                            itemTpl: [
                                '<tpl for=".">',
                                '    <div class="gallery-item">',
                                '		<img src="DefaultPreview.jpg" />',
                                '		<div class="item-title">{title}</div>',
                                '		<div class="item-description">{description}</div>',
                                '    </div>',
                                '</tpl>'
                            ],
                            store: 'GalleryItems',
                            listeners: {
                                itemclick: {
                                    fn: me.onItemsItemClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onItemsItemClick: function(dataview, record, item, index, e, eOpts) {
        var selected = record.data,
            gallery = dataview.up('gallery');
        
        gallery.onSelect(selected);
    },

    load: function(params) {
        var gallery = this;
        
    },

    onSelect: function(item) {
        Ext.Msg.alert(item.title);
    }

});